### PR TITLE
Update README with correct node version

### PR DESCRIPTION
**Pull request by rafalstapinski**
Does not work with node v7.9 or v7.10 needs v8.1.0

## Pull request checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I have resolved any merge conflicts. Confirmation: ____

## What's in this pull request?

>...

### CODE REVIEW

**Comment by paberr** [comment]
We are actually running three of our seed nodes with node v7.10.0.
Can you provide more details on why you think it does not work with these versions?

**Comment by rafalstapinski** [comment]
I've tried running the client using 7.9 and 7.10 and was getting a node error listing that node/npm was out of date when installing dependencies, and a generic node error when trying to run the client. Issue was resolved when I switched to 8.1.0

**Comment by paberr** [comment]
Do you still have the output of npm? I am unable to reproduce this behavior.

**Comment by rafalstapinski** [comment]
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.4.0-28-generic
npm ERR! argv "/home/rafal/.nvm/versions/node/v7.10.0/bin/node" "/home/rafal/.nvm/versions/node/v7.10.0/bin/npm" "install"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! file /home/rafal/.npm/globule/0.1.0/package/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected end of input at 48:24
npm ERR!     "lodash": "~1.0.1"
npm ERR!                       ^
npm ERR! File: /home/rafal/.npm/globule/0.1.0/package/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

**Comment by paberr** [comment]
Thanks, I suppose this is a problem in the package.json file.
Could you replace the line `"ws": ""` by `"ws": "*"` and try it again?
I believe that this might fix the issue.

**Comment by rafalstapinski** [comment]
This was an issue inside the globule package.json file, the last two closing brackets were not in the file.

**Pull request closed without merging**
