### PR TITLE
Fix README.md URL in ISSUE_TEMPLATE.md

### PR DESCRIPTION
**Pull request by miclaus**
## Pull request checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I have resolved any merge conflicts. Confirmation: ____

## What's in this pull request?

I've noticed that the link for `README.md` in `ISSUE_TEMPLATE.md` doesn't work as expected. I've replaced it with the respective absolute path.

### CODE REVIEW

**Comment by miclaus** [comment]
I'm wondering why the revert ?

**Comment by paberr** [comment]
Sorry, I might have accidentally clicked on revert. At least this was not intentional.
Thanks for pointing this out, I might not have noticed it.
I'll basically revert the revert.

**Comment by paberr** [comment]
Okay, it turns out GitHub automatically created a branch for the revert. But since, we never merged it, your changes are unaffected.
I will simply delete the revert branch.

**Comment by miclaus** [comment]
Cool thanks !

Glad to help a tiny bit.

**Pull request merged**
