### PR TITLE
[Unused] Automatic CPU feature detection and native module selection

### PR DESCRIPTION
**Pull request by terorie**
**Warning: Unused pull request**

Because of failing CI builds, this PR is moved to #440

### CODE REVIEW

**Comment by terorie** [comment]
Attention macOS users:
Some versions of Xcode ship a version of Clang that crashes when compiling the source with `-mavx512f`.
If you experience crashes when compiling the code on macOS, use a newer build of clang:
```
$ brew install llvm
$ export CC=/usr/local/opt/llvm/bin/clang
$ export CXX=/usr/local/opt/llvm/bin/clang++
$ yarn
```

**Comment by terorie** [comment]
I also have future plans to include all versions in one `.node` by rewriting performance-critical Argon2d sections in assembly.
Let me know if you're interested.

**Comment by terorie** [comment]
Test is failing because the testing environment of `trusty` has an old version of GCC that doesn't support `-mavx512f` yet :(

**Comment by maestroi** [comment]
only miss AVX in your PR checklist i see AVX2 not AVX but if i read code correctly it does AVX right?

**Comment by terorie** [comment]
`argon2/opt.c` doesn't target AVX.

**Comment by terorie** [comment]
@maestroi Adding a AVX build is easy. I doubt it will have any performance benefits though because after pre-processing, the code would be SSE2 intrinsics. If someone is willing to test performance differences, I'll add it though.

**Comment by jeffesquivels** [comment]
> Test is failing because the testing environment of `trusty` has an old version of GCC that doesn't support `-mavx512f` yet :(

@terorie #439 should fix this problem.

Besides that, the only other change I can think of is that you should remove [this line](https://github.com/nimiq-network/core/blob/master/travis-script.sh#L19) as `build/Release/nimiq_node_generic.node` doesn't exists anymore after your changes.

**Comment by terorie** [comment]
@jeffesquivels Good catch, I merged #439 and removed the copy from the Travis script!

**Comment by terorie** [comment]
I think something's wrong with the Travis CI cache …
The integration tests fail because `gcc-4.9` cannot be found:
https://travis-ci.org/terorie/nimiq-core/jobs/428149784#L602

**Comment by terorie** [comment]
This PR is moved to #440 !

**Pull request closed without merging**
