### PR TITLE
fix test script in package.json

### PR DESCRIPTION
**Pull request by Bettelstab**
## Pull request checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I have resolved any merge conflicts.

## What's in this pull request?

Makes `yarn test` work again.

### CODE REVIEW

**Comment by paberr** [comment]
This means we commit to using yarn. But we do that anyway in our README. ;)

**Comment by Bettelstab** [comment]
> This means we commit to using yarn. But we do that anyway in our README. ;)
My thoughts exactly :D

> Apparently there's a way to make it use whichever tool was used to run it:
> https://stackoverflow.com/questions/41647961/package-json-scripts-that-work-with-npm-and-yarn
Seems not to work on windows, or we have to use this yarpm?

**Comment by terorie** [comment]
I know it's just a `test` command and it probably doesn't matter but https://pnpm.js.org also exists and I use it because it's faster than yarn 

Maybe you can do `./node_modules/.bin/jasmine && ./node_modules/.bin/gulp test` instead?

**Comment by Bettelstab** [comment]
Like this then, to keep it simple? :p

**Pull request merged**
