### PR TITLE
Add volatile consensus options to NodeJS client

### PR DESCRIPTION
**Pull request by terorie**
~~Adds `volatile-full`, `volatile-light` and `volatile-nano` consensus options to config.~~

Adds a flag for running in `--volatile` mode

### CODE REVIEW

**Comment by sisou** [comment]
I don't think the `volatile-full` option is a good idea. This only really works for nano consensus, maybe still for light.

**Comment by terorie** [comment]
@sisou Afaik, the light state is only about 100 MB, so it'd be really nice to have.

`volatile-full` is pretty useless for main net, I agree.

**Comment by styppo** [comment]
@terorie Thanks for contributing this 👍I like the idea of exposing the volatile storage backend through the command line. However, I think it would be nicer if we had a `--volatile` command line option (which enables volatile storage for the selected consensus type) instead of modelling it as a new consensus type (I know that it is that way internally, but we don't have to expose it that way).

**Comment by terorie** [comment]
@styppo True, that way it's cleaner. I'm going to push the changes later.
Should we abort or print a warning if `--volatile --type=full` is used?

Like the `console.error("Cannot use volatile storage in full mode"); process.exit(1)` at the top of `index.js`

**Comment by styppo** [comment]
I cannot really imagine a use case where using volatile full mode makes sense (except for testing maybe), so I think it's ok to abort if that combination is used.

**Pull request merged**
