### PR TITLE
Fix to Dockerfile & separated Dockerfiles for dumb & full node

### PR DESCRIPTION
**Pull request by cinooo**
## Pull request checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I have resolved any merge conflicts.

## What's in this pull request?

Previous Dockerfile and instructions is not so helpful and wasn't able to build properly. I have separated it into two separate Dockerfile's with instructions on how to build a full node as well as a dumb node, with more detailed instructions on how to build and run them.

This has been tested on an Amazon Linux AMI.

### CODE REVIEW

**Comment by cinooo** [comment]
Please note that I also added the following lines into the core build instructions of the Dockerfiles:

```
RUN npm install -g node-gyp
RUN node-gyp configure
RUN node-gyp build
RUN node_modules/.bin/gulp prepare-packages
```

I'm not sure if this is the proper way to build but it was the only way I could get past a build issue complaining about nimiq_node missing

**Comment by cinooo** [comment]
Are the tests currently broken in master? My changes should not have affected them

**Comment by sisou** [comment]
Yes, it's just the Safari test that fails. It fails most of the time. We are restarting it to make it not fail this time ;) no worries.

**Comment by styppo** [comment]
We reworked our Dockerfiles in c7be479a40de43ca4c5acefe5036cfa8434e4d00 and improved the documentation. We do not intend to supply a Dockerfile with pre-configured _dumb_ protocol as we do not want to encourage usage of this type of client.

**Pull request closed without merging**
